In [1]:
# overloading
def sum_num(*args):
    result=0
    for num in args:
        result+=num
    print("sum:",result)
print("Similar to method overloading concept")
print("Single argument->",end="")
sum_num(10)
print("Two argument->",end="")
sum_num(10,20)
print("multiple argument->",end="")
sum_num(10,20,30,40,50)

Similar to method overloading concept
Single argument->sum: 10
Two argument->sum: 30
multiple argument->sum: 150


In [4]:
def fun(a):
    print("Hello")
def fun(a,b):
    print("Hi How are you")
def fun(a,b,c):
    print("Welcome")
fun(10,20,30)    

Welcome


In [6]:
# overriding
class A:
    def first(self):
        print("first function of class A")
    def second(self):
        print("Second function of class A")
class B(A):
    def first(self):  #overridden method
        print("Redefined function of class A in class B")
    def display(self):
        print("Display function of child class")
obj=B()
obj.first()
obj.second()
obj.display()
A().first()

Redefined function of class A in class B
Second function of class A
Display function of child class
first function of class A


In [10]:
# operator overloading
class A:
    def __init__(self,a):
        self.a=a
    def __add__(self,other):
        return self.a+other.a
obj1=A(5)
obj2=A(3)
obj3=A("Hello")
obj4=A("Hii")
print(obj1+obj2)
print(obj3+obj4)
print(obj1.__add__(obj2))
print(obj3.__add__(obj4))
print(A.__add__(obj1,obj2))
print(A.__add__(obj3,obj4))

8
HelloHii
8
HelloHii
8
HelloHii


In [12]:
# comparison operator
class A:
    def __init__(self,a):
        self.a=a
    def __gt__(self,other):
        if self.a>other.a:
            return True
        else:
            return False
obj1=A(8)
obj2=A(7)
if obj1>obj2:
    print("Obj1 is greater")
else:
    print("Obj2 is greater")

Obj1 is greater


In [18]:
# program-1
class A:
    def __init__(self,a):
        self.a=a
    def __mul__(self,other):
        return self.a*other.a
    def __floordiv__(self,other):
        return self.a//other.a
    def __lt__(self,other):
        if self.a<other.a:
            return True
        else:
            return False
    def __eq__(self,other):
        if self.a==other.a:
            return True
        else:
            return False
        
obj1=A(9)
obj2=A(1)
print(obj1*obj2)
print(obj1//obj2)
print(obj1.__mul__(obj2))
print(obj1.__floordiv__(obj2))
if obj1<obj2:
    print("Obj1 is less than obj2")
else:
    print("Obj1 is greater")
if obj1==obj2:
    print("Obj1 is equal to obj2")
else:
    print("Obj1 is not equal to obj2")    
    


9
9
9
9
Obj1 is greater
Obj1 is not equal to obj2


In [19]:
class parent:
    def func1(self):
        print("Hello parent")
class child(parent):
    def func2(self):
        print("Hello child")
obj=child()
obj.func1()
obj.func2()

Hello parent
Hello child


In [20]:
class parent1:
    def func1(self):
        print("hello parent1")
class parent2:
    def func2(self):
        print("hello parent2")

class child(parent1,parent2):
    def func3(self):
        print("Hello child")
obj=child()
obj.func1()
obj.func2()
obj.func3()

hello parent1
hello parent2
Hello child


In [23]:
class parent1:
    def func1(self):
        print("hello parent1")
class parent2:
    def func2(self):
        print("hello parent2")
class parent3:
    def func2(self):
        print("hello parent3")
        
class child(parent1,parent3,parent2):
    def func3(self):
        print("Hello child")
obj=child()
obj.func1()
obj.func2()
obj.func3()
print(child.__mro__)

hello parent1
hello parent3
Hello child
(<class '__main__.child'>, <class '__main__.parent1'>, <class '__main__.parent3'>, <class '__main__.parent2'>, <class 'object'>)


In [24]:
# multilevel inheritance
class grandparent:
    def func1(self):
        print("Hello Grandparent")
class parent(grandparent):
    def func2(self):
        print("Hello parent")
class child(parent):
    def func3(self):
        print("hello child")
obj=child()
obj.func1()
obj.func2()
obj.func3()

Hello Grandparent
Hello parent
hello child


In [26]:
class parent:
    def func1(self):
        print("hello parent")
class child1(parent):
    def func2(self):
        print("Hello child1")
class child2(parent):
    def func3(self):
        print("Hello child2")
obj1=child1()
obj1.func1()
obj1.func2()
obj2=child2()
obj2.func1()
obj2.func3()

hello parent
Hello child1
hello parent
Hello child2


In [27]:
# hybrid
class parent1:
    def func1(self):
        print("Hello parent1")
class parent2:
    def func2(self):
        print("Hello parent2")  
class child1(parent1):
    def func3(self):
        print("Hello child1")
class child2(child1,parent2):
    def func4(self):
        print("Hello child2")   
obj1=child1()
obj1.func1()
obj1.func3()
obj2=child2()
obj2.func1()
obj2.func2()
obj2.func3()
obj2.func4()

Hello parent1
Hello child1
Hello parent1
Hello parent2
Hello child1
Hello child2


In [1]:
# 24/12/25
# super()
class parent:
    def __init__(self):
        self.attr1=50
        self.attr2=60
class child(parent):
    def __init__(self):
        super().__init__()
        self.attr3=45
obj=child()
print(obj.attr3)
print(obj.attr1)
print(obj.attr2)

45
50
60


In [2]:
class parent:
    def __init__(self):
        self.attr1=50
        self.attr2=60
class child(parent):
    def __init__(self):
        parent.__init__(self)
        self.attr3=45
obj=child()
print(obj.attr3)
print(obj.attr1)
print(obj.attr2)

45
50
60


In [3]:
class parent:
    def display(self):
        print("Hello parent")
class child(parent):
    def display(self):
        super().display()
        print("Hello child")
obj=child()
obj.display()

Hello parent
Hello child


In [4]:
# issubclass()
class parent:
    def func1(self):
        print("Hello parent")
class child(parent):
    def func2(self):
        print("Hello child")
print(issubclass(child,parent))
print(issubclass(parent,child))

        

True
False


In [5]:
# isinstance()
A=child()
B=parent()
print(isinstance(A,child))
print(isinstance(A,parent))
print(isinstance(B,child))
print(isinstance(B,parent))


True
True
False
True


In [7]:
# MRO
class A:
    def rk(self):
        print("class A")
class B(A):
    def rk(self):
        print("class B")
class C(A):
    def rk(self):
        print("class C")
r=B()
r.rk()

class B


In [10]:
class A:
    def rk(self):
        print("class A")
class B(A):
    def rk(self):
        print("class B")
class C(A):
    def rk(self):
        print("class C")
class D(B,C):
    pass
r=D()
r.rk()
D.__mro__
D.mro()

class B


[__main__.D, __main__.B, __main__.C, __main__.A, object]

In [11]:
 class p1:
        def foo(self):
            print("foo from p1")
class p2:
    def foo(self):
        print("foo from p2")
    def bar(self):
        print("bar from p2")
class c1(p1):
    pass
class c2(p2):
    def bar(self):
        print("bar from c2")
class GC(c1,c2):
    pass
obj=GC()
obj.bar()
obj.foo()
GC.__mro__

bar from c2
foo from p1


(__main__.GC, __main__.c1, __main__.p1, __main__.c2, __main__.p2, object)

In [12]:
class p1:
        def foo(self):
            print("foo from p1")
class p2:
    def foo(self):
        print("foo from p2")
    def bar(self):
        print("bar from p2")
class c1(p1):
    pass
class c2(p1):
    def bar(self):
        print("bar from c2")
class GC(c1,c2):
    pass
obj=GC()
obj.bar()
obj.foo()
GC.__mro__

bar from c2
foo from p1


(__main__.GC, __main__.c1, __main__.c2, __main__.p1, object)

In [13]:
class p1:
        def foo(self):
            print("foo from p1")
class p2:
    def foo(self):
        print("foo from p2")
    def bar(self):
        print("bar from p2")
class c1(p1,p2):
    pass
class c2(p1,p2):
    def bar(self):
        print("bar from c2")
class GC(c1,c2):
    pass
obj=GC()
obj.bar()
obj.foo()
GC.__mro__

bar from c2
foo from p1


(__main__.GC, __main__.c1, __main__.c2, __main__.p1, __main__.p2, object)

In [14]:
class p1:
        def foo(self):
            print("foo from p1")
class p2:
    def foo(self):
        print("foo from p2")
    def bar(self):
        print("bar from p2")
class c1(p1,p2):
    pass
class c2(p1):
    def bar(self):
        print("bar from c2")
class GC(c1,c2):
    pass
obj=GC()
obj.bar()
obj.foo()
GC.__mro__

bar from c2
foo from p1


(__main__.GC, __main__.c1, __main__.c2, __main__.p1, __main__.p2, object)

In [15]:
class p1:
        def foo(self):
            print("foo from p1")
class p2:
    def foo(self):
        print("foo from p2")
    def bar(self):
        print("bar from p2")
class c1(p1,p2):
    pass
class c2(p2):
    def bar(self):
        print("bar from c2")
class GC(c1,c2):
    pass
obj=GC()
obj.bar()
obj.foo()
GC.__mro__

bar from c2
foo from p1


(__main__.GC, __main__.c1, __main__.p1, __main__.c2, __main__.p2, object)

In [16]:
class p1:
        def foo(self):
            print("foo from p1")
class p2:
    def foo(self):
        print("foo from p2")
    def bar(self):
        print("bar from p2")
class c1(p1,p2):
    pass
class c2(p2,p1):
    def bar(self):
        print("bar from c2")
class GC(c1,c2):
    pass
obj=GC()
obj.bar()
obj.foo()
GC.__mro__

TypeError: Cannot create a consistent method resolution
order (MRO) for bases p1, p2

In [25]:
from abc import ABC,abstractmethod
class shape(ABC):
    def __init__(self,shape_name):
        self.shape_name=shape_name
    @abstractmethod    
    def draw(self): #abstractmethod
        pass
class circle(shape):
    def __init__(self):
        super().__init__("circle")
    def draw_circle(self):
        print("Drawing:",self.shape_name)
    def draw(self):
        pass
obj=circle()
obj.draw_circle()

Drawing: circle


In [ ]:
# program-2
class Book:
    author=[]
    def __init__(self):
        self.name=input("Enter book name:")
        self.no_author=int(input("Enter no of authors:"))
        for i in range(self.no_author):
            s=input("Enter name of authors:")
            self.author.append(s)
        self.publisher=input("Enter publisher name:")
        self.isbn=int(input("Enter book no.:"))
        self.year=int(input("Enter year of publish: "))
    def display(self):
        print("name of book: ",self.name)
        print("Numbers of authors: ",self.no_author)
        print("List of authors: ",self.author)
        print("name of publisher: ",self.publisher)
        print("number of book: ",self.isbn)
        print("year of publish the book: ",self.year)
class coursebook(Book):
    def __init__(self):
        super().__init__()
        self.course_name=input("Enter your course name: ")
    def display(self):
        super().display()
        print("Your course name is: ",self.course_name)
obj=coursebook()
obj.display()

In [ ]:
class student:
    def __init__(self,rollno,name,age,totalmarks):
        self.rollno=rollno
        self.name=name
        self.age=age
        self.totalmarks=totalmarks
    def display(self):
        print("Roll no:",self.rollno)
        print("name:",self.name)
        print("age:",self.age)
        

In [1]:
# 26/12/25
# program-4
class Bill:
    rates = {"HDD":5000, "RAM":2000, "Printer":6000, "Pendrive":800}
    items = {"HDD":0, "RAM":0, "Printer":0, "Pendrive":0}
    
    for i,j in rates.items():
        print(i,j)
        accept = input("Want this item? (Y/N)").upper()
        if accept == 'Y':
            items[i] = int(input("Enter No. of "+i+" 's: '"))*rates[i]
        print()
    
    def __init__(self):
        print("1. Cash Payment")
        print("2. Cheque Payment")
        payment_method = int(input("Enter Method 1/2:"))
        if payment_method == 1:
            cashpayment()
        else:
            chequepayment()

class cashpayment(Bill):
    def __init__(self):
        print()
        print("Payment Method is Cash")
        sum=0
        for i,j in self.items.items():
            sum += j
        print("Total Amount to Pay:",sum)
        d = {"2000 Rs Notes:":2000 , "500 Rs Notes:":500 , "100 Rs Notes:":100,
            "50 Rs Notes:":50,"20 Rs Notes:":20, "10 Rs Notes:":10}
        print()
        for i,j in d.items():
            if sum >= j:
                print(i + ":" ,sum//j)
                sum = sum%j

class chequepayment(Bill):
    def __init__(self):
        print()
        print("Payment Method is Cheque")
        sum=0
        for i,j in self.items.items():
            sum += j
        print("Total Amount to Pay:",sum)
        print()
        Chq_No = int(input("Enter Cheque Number:"))
        Bank = input("Enter Bank Name:")
        print()
        print("Cheque Details:")
        print("Cheque Number:",Chq_No)
        print("Bank Name:",Bank)
customer = Bill()    

HDD 5000
Want this item? (Y/N)y
Enter No. of HDD 's: '2

RAM 2000
Want this item? (Y/N)1

Printer 6000
Want this item? (Y/N)y
Enter No. of Printer 's: '1

Pendrive 800
Want this item? (Y/N)y
Enter No. of Pendrive 's: '3

1. Cash Payment
2. Cheque Payment
Enter Method 1/2:1

Payment Method is Cash
Total Amount to Pay: 18400

2000 Rs Notes:: 9
100 Rs Notes:: 4


-  NUMPY

In [2]:
import numpy as np
import sys
s=range(1000)
print("size of each element of list in bytes:",sys.getsizeof(s))
print("size of whole list in bytes:",sys.getsizeof(s)*len(s))

size of each element of list in bytes: 48
size of whole list in bytes: 48000


In [3]:
d=np.arange(1000)
print("size of each element of Numpy array in bytes:",d.itemsize)
print("size of whole Numpy array in bytes:",d.itemsize*d.size)

size of each element of Numpy array in bytes: 4
size of whole Numpy array in bytes: 4000


In [4]:
import numpy as np
arr=np.array(42)
print(arr)
print(type(arr))
print(arr.ndim)

42
<class 'numpy.ndarray'>
0


In [29]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr[3])
print(arr[2]+arr[1])
print(arr[:3])
print(arr[0:5:2])
print(arr[-3:-1])
print(arr[-3:-1:-1])

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
4
5
[1 2 3]
[1 3 5]
[3 4]
[]


In [21]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr[0,2])
print(arr[1][3])
print(arr[1,:3])
print(arr[:1,:3])
print(arr[1,3])
print(arr[1:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>
2
3
9
[6 7 8]
[[1 2 3]]
9
[[ 6  7  8  9 10]]


In [9]:
import numpy as np
arr=np.array([[[1,2,3,4,5]]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr[0,0,4])

[[[1 2 3 4 5]]]
<class 'numpy.ndarray'>
3
5


In [31]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr[0,1,1])
print(arr[1,0,2])
print(arr[-2,-2,-2])
print(arr[-1,1,-1])
print(arr[0,:1,:1])
print(arr[:1,:1,:1])
print(arr[1,1,:1])
print(arr[0:5:2])
print(arr[0:2,0:2,0:2])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
3
5
9
2
12
[[1]]
[[[1]]]
[10]
[[[1 2 3]
  [4 5 6]]]
[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]
(2, 2, 3)


In [32]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr.shape)

(2, 2, 3)


In [36]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr.shape)


(5,)


In [37]:
import numpy as np
arr=np.array([1,2,3,4,5],ndmin=5)
print(arr)
print(arr.shape)

[[[[[1 2 3 4 5]]]]]
(1, 1, 1, 1, 5)


In [38]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
new=arr.reshape(2,3)
print(new)

[[1 2 3]
 [4 5 6]]


In [5]:
# 30/12/25
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=arr.reshape(2,3,1)
print(newarr)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


In [6]:
# base is use for find original array
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=arr.reshape(2,3,1).base
print(newarr)

[1 2 3 4 5 6]


In [7]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=arr.reshape(2,-1)
print(newarr)

[[1 2 3]
 [4 5 6]]


In [8]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=arr.reshape(-1,3)
print(newarr)

[[1 2 3]
 [4 5 6]]


In [9]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
for x in arr:
    print(x)

1
2
3
4
5
6


In [12]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
for x in arr:
    for j in x:
        print(j)

1
2
3
4
5
6
7
8


In [14]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    for j in x:
        for i in j:
            print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [18]:
# function for print elements in array without use of multiple loops
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr):
    print(x)
print("3-dimensial array elements using function")    
arr1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in np.nditer(arr1):
    print(x)
    

1
2
3
4
5
6
7
8
3-dimensial array elements using function
1
2
3
4
5
6
7
8
9
10
11
12


In [21]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[0:1,::2]):
    print(x)
for x in np.nditer(arr[0:1,1::2]):
    print(x)  
for x in np.nditer(arr[:,::2]):
    print(x)          

1
3
2
4
1
3
5
7


# Built-in Functions


### - concatenate()

In [22]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.array([7,8,9])
arr=np.concatenate((arr1,arr2,arr3))
print(arr)

[1 2 3 4 5 6 7 8 9]


In [29]:
arr1=np.array([[1,2],[5,6]])
arr2=np.array([[3,4],[7,8]])
arr=np.concatenate((arr1,arr2))
print(arr)
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)

[[1 2]
 [5 6]
 [3 4]
 [7 8]]
[[1 2]
 [5 6]
 [3 4]
 [7 8]]


In [27]:
arr1=np.array([[1,2],[5,6]])
arr2=np.array([[3,4],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


### - split


In [30]:
arr1=np.array([1,2,3,4])
newarr=np.array_split(arr1,4)
print(newarr)

[array([1]), array([2]), array([3]), array([4])]


In [31]:
arr1=np.array([1,2,3,4])
newarr=np.array_split(arr1,3)
print(newarr)

[array([1, 2]), array([3]), array([4])]


In [32]:
arr1=np.array([1,2,3,4])
newarr=np.array_split(arr1,5)
print(newarr)

[array([1]), array([2]), array([3]), array([4]), array([], dtype=int32)]


In [33]:
arr1=np.array([1,2,3,4])
newarr=np.array_split(arr1,2)
print(newarr)

[array([1, 2]), array([3, 4])]


In [38]:
arr1=np.array([[1,2],[3,4],[5,6],[7,8]])
newarr1=np.array_split(arr1,4,axis=1)
print(newarr1)
newarr2=np.array_split(arr1,3,axis=1)
print(newarr2)
newarr3=np.array_split(arr1,2,axis=1)
print(newarr3)


[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]]), array([], shape=(4, 0), dtype=int32), array([], shape=(4, 0), dtype=int32)]
[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]]), array([], shape=(4, 0), dtype=int32)]
[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]


### - where                                                                                                                                                                                                                                                                      

In [40]:
arr1=np.array([1,2,3,4,5,6,4,2,3])
x=np.where(arr1==4)
print(x)
y=np.where(arr1%2==0)
print(y)

(array([3, 6], dtype=int64),)
(array([1, 3, 5, 6, 7], dtype=int64),)


In [41]:
arr1=np.array([[1,2],[3,4],[5,6],[4,8]])
x=np.where(arr1==4)
print(x)

(array([1, 3], dtype=int64), array([1, 0], dtype=int64))


In [42]:
arr1=np.array([[[1,2,3],[4,5,7]],[[7,8,9],[7,11,12]]])
x=np.where(arr1==7)
print(x)

(array([0, 1, 1], dtype=int64), array([1, 0, 1], dtype=int64), array([2, 0, 0], dtype=int64))


### - sort()

- in this function default value of axis is -1

In [43]:
arr1=np.array([1,2,3,4,5,6,4,2,3])
print(np.sort(arr1))
arr2=np.array(["apple","cherray","banana"])
print(np.sort(arr2))
arr3=np.array([True,False,True])
print(np.sort(arr3))

[1 2 2 3 3 4 4 5 6]
['apple' 'banana' 'cherray']
[False  True  True]


In [47]:
arr=np.array([[3,4,2],[1,7,3],[4,2,5]])
print(np.sort(arr))
print(np.sort(arr,axis=0))
print(np.sort(arr,axis=1))   #same as normal sorting


[[2 3 4]
 [1 3 7]
 [2 4 5]]
[[1 2 2]
 [3 4 3]
 [4 7 5]]
[[2 3 4]
 [1 3 7]
 [2 4 5]]


In [51]:
arr1=np.array([[[3,2,8],[7,9,3]],[[6,7,2],[9,6,4]]])
print(np.sort(arr1))
print(np.sort(arr1,axis=0))
print(np.sort(arr1,axis=1))
print(np.sort(arr1,axis=2))   #same as normal sorting

[[[2 3 8]
  [3 7 9]]

 [[2 6 7]
  [4 6 9]]]
[[[3 2 2]
  [7 6 3]]

 [[6 7 8]
  [9 9 4]]]
[[[3 2 3]
  [7 9 8]]

 [[6 6 2]
  [9 7 4]]]
[[[2 3 8]
  [3 7 9]]

 [[2 6 7]
  [4 6 9]]]


# Random Module

### - randint()

In [54]:
from numpy import random
x=random.randint(100)   #here 100 is excluded
print(x)

31


In [56]:
from numpy import random
x=random.randint(10,100)  
print(x)

24


In [61]:
from numpy import random
x=random.randint(10,100,size=(5))  
print(x)
y=random.randint(1,100,size=(3,5))  
print(y)
z=random.randint(10,100,size=(3,3,2))  
print(z)

[15 26 64 79 13]
[[75  8 80  6 94]
 [ 1 30 59 90 36]
 [89 75 45 81 52]]
[[[71 94]
  [45 74]
  [14 65]]

 [[42 86]
  [47 97]
  [11 89]]

 [[35 74]
  [52 10]
  [48 81]]]


### - rand()

- it takes range 0 to 1 by default where 1 is excluded

In [64]:
from numpy import random
x=random.rand()
print(x)
y=random.rand(5)
print(y)
z=random.rand(3,5)
print(z)

0.21324817303842825
[0.98781541 0.52365582 0.04129608 0.2638063  0.22361893]
[[0.66331301 0.3519248  0.80926992 0.53433732 0.1103653 ]
 [0.57384752 0.2312529  0.84165044 0.21789207 0.67176232]
 [0.32405013 0.25563004 0.52366169 0.634862   0.53555227]]


### - choice()

In [67]:
x=random.choice([1,3,5,7,9])
print(x)
x1=random.choice([1,3,5,7,9],size=(5))
print(x1)
x2=random.choice([1,3,5,7,9],size=(3,5))
print(x2)

3
[7 7 1 5 7]
[[9 9 3 5 3]
 [3 7 1 3 5]
 [3 3 3 3 3]]


In [71]:
# program-5
x=random.randint(1,100)  
count=7
while(count!=0):
    n=int(input("Enter a number to check "))
    if(x==n):
        print("You guess correct number")
        break
    else:
        print("you guess wrong number")
        count=count-1
        print("remaining attemps are:",count)
        if(x>n):
            print("your number is higher than you think!!")
        else:
            print("Your number is lower than you think!!")
if(count==0):
    print("game over!!")
    print("Your correct number is",x)        
    

Enter a number to check 17
you guess wrong number
remaining attemps are: 6
Your number is lower than you think!!
Enter a number to check 15
you guess wrong number
remaining attemps are: 5
Your number is lower than you think!!
Enter a number to check 12
you guess wrong number
remaining attemps are: 4
Your number is lower than you think!!
Enter a number to check 9
you guess wrong number
remaining attemps are: 3
Your number is lower than you think!!
Enter a number to check 7
you guess wrong number
remaining attemps are: 2
your number is higher than you think!!
Enter a number to check 8
You guess correct number
