# Part-1 UI Creation & Layout Fundamentals

In [5]:
%%writefile 1_hello.py
import streamlit as st
st.set_page_config(page_title='Hello Streamlit',page_icon='⚾',layout='wide')
st.title("Welcome to Streamlit")
st.header("This is header")
st.subheader("This is subheader")
st.text("st.text() is used for simple fixed width text")
st.write("st.write() is more flexible and can display text,numbers,dataframe etc")
st.markdown("**st.markdown()** lets you use markdown for **rich text** ")

code_example="""
def add(a,b):
    return a+b
result=add(5,7)
print(result)
"""
st.code(code_example,language='python')
# language=C/java.....default=python

Overwriting 1_hello.py


In [2]:
pwd

'C:\\Users\\LJENG'

In [10]:
%%writefile 2_layout_basics.py
import streamlit as st
st.set_page_config(page_title='Faculty Profile',page_icon='⚾',layout='wide')
st.title("❄Faculty Profile Demo")
st.markdown("This example shows how to use **sidebar**,**columns** and **expanders**")

st.sidebar.header("Profile Settings")
faculty_name=st.sidebar.text_input("Faculty Name",'Tejas Thakkar')
department=st.sidebar.selectbox('Department',['CE','IT','CSE','AIML'])
experience=st.sidebar.slider("Years of Experience",0,40,10)

st.sidebar.markdown("---")
st.sidebar.write("You can put filters,toggles etc in sidebar.")

col1,col2=st.columns([1,2])

with col1:
    st.subheader("Basic Info")
    st.write(f"**Name:** {faculty_name}")
    st.write(f"**Department:** {department}")
    st.write(f"**Experience:** {experience} years")
    
with col2:
    st.subheader("About")
    st.markdown("""
    Use this area to show detailed information about the faculty member,
    such as research interest,publications and courses handled.""")
    
with st.expander("Show Courses Handled"):
    st.write(" Python-1 ")
    st.write(" Python-2 ")
    st.write(" Digital Electronics ")
    st.write(" PS ")
with st.expander("Show Publications"):
    st.write("1. Research Paper A (2024)")
    st.write("2. Research Paper B (2025)")

Overwriting 2_layout_basics.py


# Part 2: Input Widgets & Interactivity

# Text Inputs

In [12]:
%%writefile 3_text_inputs.py
import streamlit as st

st.title("Text Input Demo")
name=st.text_input("Enter your name: ")
comments=st.text_area("Any Comments or Feedback ?")

st.write("**Live Output")
if name:
    st.write(f"Hello,**{name}** 🖐")
if comments:
    st.write(comments)
             

Overwriting 3_text_inputs.py


# Number Input & Sliders

In [13]:
%%writefile 4_number_inputs.py
import streamlit as st

st.title("Number Input & Slider Demo")

age=st.number_input("Enter your Age:",min_value=0,max_value=100,value=25)
rating=st.slider("Rate this Session(1-10):",min_value=1,max_value=10,value=7)

st.write(f"**Your age is:**{age}")
st.write(f"**You Rated this Session:** {rating}/10")

Writing 4_number_inputs.py


# Selection Widgets

In [17]:
%%writefile 5_selection_widgets.py
import streamlit as st

st.title("Selection Widget Demo")
course=st.selectbox("Select Course:",['python-1','FSD-1','PS','DE'])
preferred_days=st.multiselect(
"preferred Days for Extra Lectures",
['Monday','Tuesday','wednesday','Thursday','Friday','Saturday'])

delievery_mode=st.radio("preferred Delievery Mode:",
                        ['Offline','Online','Hybrid'])

subscribe=st.checkbox("Subscribe to Course updates?")

st.write("---")
st.write(f"**Course:** {course}")
st.write(f"**Preferred Days:**{','.join(preferred_days) if preferred_days else 'None'}")
st.write(f"**Delievery Mode:** {delievery_mode}")
st.write(f"**Subscribed:** {'Yes' if subscribe else 'No'}")        
         

Overwriting 5_selection_widgets.py


In [ ]:
# 7/1/2026

In [6]:
%%writefile 6_Notice_Board.py
import streamlit as st
from datetime import date
st.set_page_config(page_title='Notice Board',page_icon='⚾',layout='wide')
st.title("Notice Board")
st.sidebar.header("Filter Notices")
selected=st.sidebar.selectbox("Notice Category",['All','Exams','Workshops','Internship'])
show_past=st.sidebar.checkbox("Show Past Notices:",value=True)

notices=[{'title':"T4 Exam Schedule",'category':'Exams','date':date(2026,1,1)},
    {'title':"Python Workshop",'category':'Workshops','date':date(2026,1,5)},
    {'title':"Internship Orientation",'category':'Internship','date':date(2026,1,3)}]


st.header("Notices")
col1,col2=st.columns([1,2])

with col1:
    st.subheader("Filter Applied")
    st.write(f"Category: **{selected}**")
    st.write(f"Include Past Notices: {show_past}")
with col2:
    st.subheader("Information")
    st.text("Below are notices after filtering")
    
for notice in notices:
    if selected!='All' and notice['category'] !=selected:
        continue
    with st.expander(f"{notice['title']} {notice['category']}"):
        st.write(f"**Date** {notice['date']}")
        st.write("Notice Details")
    
    
    

Overwriting 6_Notice_Board.py


## Example-Date,Time & File Uploader

In [7]:
%%writefile 7_date_time_file.py
import streamlit as st
from datetime import date,time

st.title("Date,Time & File Uploader Demo")

exam_date=st.date_input("Select Exam Date:",value=date.today())
start_time=st.time_input("Exam Start Time:",value=time(9,0))

upload_file=st.file_uploader("Upload CSV file",type=['csv'])
st.write(f"Selected Exam Date: {exam_date}")
st.write(f"Exam Start Time: {start_time}")

if upload_file is not None:
    st.success("File Uploaded Successfully")
    st.write("File Name:",upload_file.name)
    st.write("File Type:",upload_file.type)

Writing 7_date_time_file.py


## Example-Buttons & Download Button

In [8]:
%%writefile 8_button_demo.py
import streamlit as st
import pandas as pd

st.title("Button & Download Demo")
if st.button("Click to Generate Sample Data"):
    df=pd.DataFrame({
        'Enrollment No':[1,2,3,4,5],
        'Marks':[778,85,69,92,89]
    })
    st.write("Generated Data")
    st.dataframe(df)
    csv=df.to_csv(index=False).encode('utf-8')
    st.download_button(label='Download as CSV',data=csv,file_name='sample.csv',mime='text/csv')

Writing 8_button_demo.py


## part-3 Output Display & Matplotlib Integration

### Example - Dataframe,Table,JSON

In [9]:
%%writefile 9_display_data.py
import streamlit as st
import pandas as pd
st.title("Displaying Data in Streamlit")

data={
    'student':['A','B','C','D'],
    "Marks":[85,92,76,34],
    'Passed':[True,True,True,False]
}

df=pd.DataFrame(data)
st.subheader("st.dataframe(Interactive)")
st.dataframe(df)

st.subheader("st.table(static)")
st.table(df)

st.subheader("st.json(Structured JSON)")
st.json(data)

Writing 9_display_data.py


## Example - Media Display

In [11]:
%%writefile 10_media_display.py
import streamlit as st
st.title("Media Display Demo")
st.subheader("Image Example")
st.image('python.jpg',use_container_width=True)

st.subheader('Audio Example')
st.audio('sampleaudio.mp3')
st.subheader("Video Example")
st.video('samplevideo.mp4')

Overwriting 10_media_display.py


## Example - Status Elements & Progress

In [15]:
%%writefile 11_status_demp.py
import streamlit as st
import time
st.title("Status Element Demo")

st.success("This is success Message")
st.warning("This is Warning message")
st.error("This is error Message")
st.info("Useful Information can go here")

st.write("---")

st.subheader("Progress & Spinner Example")
if st.button("Start Long Task"):
    progress=st.progress(0)
    with st.spinner("Processing..."):
        for i in range(100):
            time.sleep(0.03)
            progress.progress(i+1)
    st.success("Task Completed")        

Overwriting 11_status_demp.py


## Example - Basic Matplotlib Charts 

In [1]:
%%writefile 12_matplotlib_basic.py
import streamlit as st
import matplotlib.pyplot as plt
import numpy as np

st.title("Matplotlib + Streamlit Demo")

x=np.arange(1,11)
y=np.random.randint(50,100,size=10)

#---------------
# Line chart
#---------------
st.subheader("Line Chart(Matplotlib)")
plt.figure(figsize=(6,4))
plt.plot(x,y,marker='o')
plt.xlabel('Student Index')
plt.ylabel('Marks')
plt.title("Marks of 10 students")
st.pyplot(plt)

plt.clf()   #for no overlapping of chart

#-----------
# Bar Chart
#------------
st.subheader("Bar Chart(Matplotlib)")
plt.figure(figsize=(5,3))
plt.bar(x,y)
plt.xlabel('Student Index')
plt.ylabel('Marks')
plt.title("Marks Bar Chart")
st.pyplot(plt)

# 9/1/26

#--------------
# Histogram
#-------------

st.subheader('Histogram')
plt.figure(figsize=(5,3))
plt.hist(y)
plt.xlabel("Student Index")
plt.ylabel('Marks')
plt.title("Marks Histogram")
st.pyplot(plt)

#--------------
# Scatter Plot
#--------------

st.subheader("Scatter Plot")
plt.figure(figsize=(5,3))
plt.scatter(x,y,marker='o')
plt.xlabel("Student Index")
plt.ylabel('Marks')
plt.title("Scatter Plot")
st.pyplot(plt)


Overwriting 12_matplotlib_basic.py


In [ ]:
# pip install matplotlib
# pip install streamlit

## Example-13 Matplotlib Streamlit Inbuilt Graphs

In [2]:
%%writefile 13_streamlit_graph.py
import streamlit as st
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

st.title("Matplotlib Streamlit Graph Demo")

marks=np.random.randint(50,100,size=10)
attendance=np.random.randint(50,100,size=10)

chart_data=pd.DataFrame({
    "Marks":marks,
    "Attendance":attendance
})

st.subheader("Line Chart")
st.line_chart(chart_data)

st.subheader("Area Chart")
st.area_chart(chart_data)

st.subheader("Bar chart")
counts,bins=np.histogram(marks,bins=3)
st.bar_chart(counts)

Writing 13_streamlit_graph.py


## TASK(FORM)

In [26]:
%%writefile 14_form.py
import streamlit as st
from datetime import date
import numpy as np
import pandas as pd  

st.set_page_config(page_title='Student Marks&Feedback',page_icon='📝',layout='wide')
st.title("📝Student Marks&Feedback")
st.header("Form")
st.subheader("1.Student Information")
col1,col2=st.columns([1,2])

with col1:
    Enrollment_number=st.text_input("Enter your enrollment number: ")
    Name=st.text_input("Enter your name:")
    
with col2:
    sem=st.selectbox("Select Sem:",['1','2','3','4','5','6','7','8'])
    div=st.text_input("Enter your div:")

exam_date=st.date_input("Select Exam Date:",value=date.today())  

st.subheader("2.Student Marks")
Python=st.number_input("Python Marks(out of 100):",min_value=0,max_value=100,value=0)
Ps=st.number_input("Ps Marks(out of 100):",min_value=0,max_value=100,value=0)
DE=st.number_input("DE Marks(out of 100):",min_value=0,max_value=100,value=0)

st.subheader("3.Feedback")
rating=st.slider("How well did you understand the subject?:",min_value=1,max_value=10,value=7)
participation=st.radio("Class Participation:",
                        ['Low','Medium','High'])
comments=st.text_area("Additional Comments")
if st.button("Submit Record"):
    df=pd.DataFrame({'Enrollment No':[ Enrollment_number],'Name':[Name],'Semester':[sem],'div':[div],
                     'Python-1':[Python],
                     'DE':[DE],'PS':[Ps],'Your Feedback':[rating],'Participation':[participation],
                     'Additional Comments':[comments]})
    st.success("Generated Data")
    st.dataframe(df)
    csv=df.to_csv(index=True).encode('utf-8')
    st.download_button(label='Download as CSV',data=csv,file_name='sample.csv',mime='text/csv')

Overwriting 14_form.py


## Task(matplotlib)

In [44]:
%%writefile 15_matplotlib_task.py
import streamlit as st
import matplotlib.pyplot as plt
import numpy as np

x=np.arange(1,11)
y=np.random.randint(50,100,size=10)

st.set_page_config(page_title='Matplotlib Task',page_icon='🟦',layout='centered')
st.title("🟦 Matplotlib Task")
plt.figure(figsize=(5,3))
x1=np.array([0,1,2,3])
y1=np.array([10,20,30,40])
plt.subplot(2,2,1)
plt.plot(x1,y1,ls=":",color="red",marker="o")
plt.xlabel("x-subplot1")
plt.ylabel("y-subplot1")
plt.title("subplot-1 Data")
st.pyplot(plt)
plt.clf() 

st.subheader("Line Chart(Matplotlib)")
plt.figure(figsize=(5,3))
plt.subplot(2,2,2)
plt.plot(x,y,marker='o')
plt.xlabel('Student Index')
plt.ylabel('Marks')
plt.title("Marks of 10 students")
st.pyplot(plt)
plt.clf()

st.subheader('Histogram')
plt.figure(figsize=(5,3))
plt.subplot(2,2,3)
plt.hist(y)
plt.xlabel("Student Index")
plt.ylabel('Marks')
plt.title("Marks Histogram")
st.pyplot(plt)
plt.clf()

st.subheader("Bar Chart(Matplotlib)")
plt.figure(figsize=(5,3))
plt.subplot(2,2,4)
plt.bar(x,y)
plt.xlabel('Student Index')
plt.ylabel('Marks')
plt.title("Marks Bar Chart")
st.pyplot(plt)
plt.clf()

Overwriting 15_matplotlib_task.py


## write a program to create a bar plot of courses vs no.of students enrolled in that course using following distionary with approprite label with x and y label and the color of the bar should be green 
data={"c":20,"c++":11,'JAVA':15,"Python":30,'FSD':45,'Javascript':10,'PHP':21,'R':14}


In [56]:
%%writefile 16_task.py
import streamlit as st
import matplotlib.pyplot as plt
import numpy as np

data={"c":20,"c++":11,'JAVA':15,"Python":30,'FSD':45}
st.subheader("Bar Chart")
plt.figure(figsize=(10,8))
for i,j in data.items():
    plt.bar(i,j,color='green')
plt.xlabel('Courses')
plt.ylabel('No.of Students')
st.pyplot(plt)
plt.clf()

st.subheader("Pie Chart")
plt.figure(figsize=(10,8))
for i,j in data.items():
    plt.pie(j)
st.pyplot(plt)    

Overwriting 16_task.py


In [50]:
import numpy as np
arr=np.array([[[4,2,3],[6,4,5]],[[9,7,2],[1,4,7]]])
print(np.short(arr))
print(np.sort(arr,axis=None))

[[[4 2 3]
  [6 4 5]]

 [[9 7 2]
  [1 4 7]]]
[1 2 2 3 4 4 4 5 6 7 7 9]
